#!/bin/bash

#
# SpringBoot
#
# chkconfig: 2345 89 9
# description: SpringBoot


#APP根目录
APP_DIR="/appfuruns/powerjob"

source /etc/rc.d/init.d/functions

RUNNING_USER=root

RETVAL=0

desc="SpringBoot powerjob-server"

start() {
  echo -e $"Starting $desc: "
  daemon --user $RUNNING_USER $APP_DIR/bin/start.sh
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch /var/lock/subsys/powerjob-server
  return $RETVAL
}

stop() {
  echo -e $"Stopping $desc: "
  daemon --user $RUNNING_USER $APP_DIR/bin/stop.sh
  RETVAL=$?
  sleep 1
  echo
  [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/powerjob-server
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $RETVAL